In [10]:
import pandas as pd
import numpy as np
file = "C:/student_health_2.csv"
df = pd.read_csv(file, encoding='cp949')
df

,ID,최종가중치,학교ID,도시규모,도시규모별분석용,학년도,광역시도,시도별,학교급별,학교명,...,키,몸무게,혈당식전mgdl,총콜레스테롤mgdl,ASTUL,ALTUL,혈색소gdl,간염검사,수축기,이완기
0,Aa011남10101,169.550665,Aa01,대도시/중소도시,특별/광역시,2015,서울,서울특별시교육청,1,서울대도초등학교,...,125.8,27.3,NaN,NaN,NaN,NaN,NaN,NaN,77.0,58.0
1,Aa011남10102,169.550665,Aa01,대도시/중소도시,특별/광역시,2015,서울,서울특별시교육청,1,서울대도초등학교,...,124.3,25.4,NaN,NaN,NaN,NaN,NaN,NaN,83.0,51.0
2,Aa011남10103,169.550665,Aa01,대도시/중소도시,특별/광역시,2015,서울,서울특별시교육청,1,서울대도초등학교,...,119.2,23.5,NaN,NaN,NaN,NaN,NaN,NaN,103.0,65.0
3,Aa011남10104,169.550665,Aa01,대도시/중소도시,특별/광역시,2015,서울,서울특별시교육청,1,서울대도초등학교,...,115.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,92.0,66.0
4,Aa011남10105,169.550665,Aa01,대도시/중소도시,특별/광역시,2015,서울,서울특별시교육청,1,서울대도초등학교,...,120.0,33.5,NaN,NaN,NaN,NaN,NaN,NaN,102.0,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3564,Aa256여60216,43.628688,Aa25,대도시/중소도시,특별/광역시,2015,서울,서울특별시교육청,1,서울창천초등학교,...,142.1,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3565,Aa256여60217,43.628688,Aa25,대도시/중소도시,특별/광역시,2015,서울,서울특별시교육청,1,서울창천초등학교,...,159.6,48.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3566,Aa256여60218,43.628688,Aa25,대도시/중소도시,특별/광역시,2015,서울,서울특별시교육청,1,서울창천초등학교,...,151.5,37.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3567,Aa256여60219,43.628688,Aa25,대도시/중소도시,특별/광역시,2015,서울,서울특별시교육청,1,서울창천초등학교,...,148.8,44.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3568,Aa256여60220,43.628688,Aa25,대도시/중소도시,특별/광역시,2015,서울,서울특별시교육청,1,서울창천초등학교,...,150.9,58.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN